# docker buildx build -f Dockerfile_312_debian --platform linux/amd64,linux/arm64 -t prikid/python_psycopg2_pandas_orjson:3.12-debian --push .

FROM python:3.12-slim-bookworm
LABEL maintainer="Serhii Riabcheniuk"
ENV PYTHONUNBUFFERED 1
ENV PYBIN /py/bin

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libpq-dev gcc python3-dev && \
    python -m venv /py && \
    ${PYBIN}/pip install --upgrade pip && \
    ${PYBIN}/pip install orjson==3.9.10 psycopg2==2.9.9 pandas==1.5.3 numpy==1.26.2 && \
    apt-get remove -y libpq-dev gcc python3-dev && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD tail -f /dev/null
