# docker buildx build -f Dockerfile_311_without_venv --platform linux/amd64,linux/arm64 -t prikid/python_psycopg2_pandas_orjson:3.11-alpine-wv --push .

FROM python:3.11-alpine3.18
LABEL maintainer="Serhii Riabcheniuk"
ENV PYTHONUNBUFFERED 1
RUN --mount=type=cache,target=/root/.cache/pip \
    apk add --update --no-cache --virtual .build-deps gcc g++ musl-dev rust cargo patchelf libpq-dev libffi-dev \
    && apk add --no-cache libpq \
    && pip install --upgrade pip \
    && pip install orjson=3.8.14 psycopg2=2.9.6 pandas=2.0.2 \
    && apk del .build-deps

CMD tail -f /dev/null
